---
- name: Install delta rpm
  yum: name=deltarpm state=present
- name: Install or update epel repo
  yum: name=epel-release state=present
- name: install pip unzip 
  yum:
    name: "{{ item }}"
    state: present
  with_items:
        - python-pip
        - unzip
        - wget
        - yum-utils
- name: Install java 8 and 11
  yum: 
    name:
       - java-1.8.0-openjdk-devel
       - java-11-openjdk-devel
    state: present
           